### ISSUE TITLE
cant open downloaded apk file

### ISSUE THREAD

**Issue by dekzitfz** [mega-arbuz/apk-release-deploy#1]
Hi, I read your great article from medium, but I have one problem.

when I download the apk from dropbox url using chrome in android devices(redirected by gmail app), the apk cant be opened, it seems the apk file is not recognized as an APK (altough it has apk extension).

and then I try to download the apk from dropbox url using my chrome on pc browser and transfer it to my android devices. now the apk file can be opened. 

this issue maybe related to this: https://stackoverflow.com/questions/3253079/cant-install-apk-from-browser-downloads

can u do something about it? thanks

**Comment by mega-arbuz** [comment]
Hi, glad you liked it :)

I fixed the download URL ("raw=1" instead of "dl=1") and I think it should work now.
It looks like this doesn't happen on all devices and I didn't notice this issue, so thanks for reporting.
