### ISSUE TITLE
Failed: upload file to Dropbox

### ISSUE THREAD

**Issue by putrarifin** [mega-arbuz/apk-release-deploy#2]
pls help why this error always show ?

**Comment by mega-arbuz** [comment]
The reason is probably that there is something wrong with the Dropbox token. I've added an error code to the fail message, so now it should show something like:
`Failed: upload file to Dropbox: 401`
Could you run again and tell which error code do you see?

**Comment by putrarifin** [comment]
thanks for reply my issue, i already fix it, its because my variable token null
