### ISSUE TITLE
issue with new gradle version

### ISSUE THREAD

**Issue by dekzitfz** [mega-arbuz/apk-release-deploy#3]
in the latest version of `com.android.tools.build:gradle` (3.4.0), the `output.json` file content is changed. `apkInfo` changed to `apkData` which lead to error getting apk info.

error:
`Traceback (most recent call last):
  File "apk-release-deploy/deploy.py", line 249, in <module>
    app_version, app_file = get_app(options.release_dir)
  File "apk-release-deploy/deploy.py", line 144, in get_app
    app_version = json_data[0]['apkInfo']['versionName']
KeyError: 'apkInfo'`

sample new content of output.json:

```json
[{"outputType":{"type":"APK"},"apkData":{"type":"MAIN","splits":[],"versionCode":1,"versionName":"1.0","enabled":true,"outputFile":"app-release.apk","fullName":"release","baseName":"release"},"path":"app-release.apk","properties":{}}]
```

**Comment by mega-arbuz** [comment]
Hi,
Thanks for noticing. I pushed a fix that fits both old an new version.
