### ISSUE TITLE
how to generetae version

### ISSUE THREAD

**Issue by ropi95** [mega-arbuz/apk-release-deploy#4]
hi i want to ask about version, im using flutter for develop the app... i use your script for publish to dropbox and send to email... how to generetate version in app using this code? because on my script always return 1.0.0 ... thank you anway

**Comment by mega-arbuz** [comment]
Hi,
the script takes the version number from a JSON file in the project's release directory.
I don't have a flutter environment yet so I don't know where they put this but you can modify the script:
First, run the script with `--release.dir` parameter pointing to flutters output directory (or any other directory that contains the version file).
Then in the `get_app` method, change the file name (line 140) to the file that has the version code.

**Comment by ropi95** [comment]
okay thank you, i have solved it by using git tags and change it using flutter build..
